# Generated by Django 2.1.2 on 2019-01-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errors',
            options={'managed': True, 'verbose_name': 'error', 'verbose_name_plural': 'errors'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'managed': True, 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['title'], name='services_title_70c191_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['short_name'], name='services_short_n_b71311_idx'),
        ),
    ]
