# Generated by Django 2.1.2 on 2019-01-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_auto_20190125_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'managed': True, 'ordering': [], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
    ]
