# Generated by Django 2.1.2 on 2019-01-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_auto_20190125_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'managed': True, 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
    ]
