# Generated by Django 2.1.2 on 2019-01-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_auto_20190125_1605'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['result_vot'], name='services_result__6ac969_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['result_spec'], name='services_result__8800e7_idx'),
        ),
    ]
