# Generated by Django 2.1.2 on 2019-01-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0005_auto_20190129_2030'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='errors',
            index=models.Index(fields=['date'], name='errors_date_5157e9_idx'),
        ),
        migrations.AddIndex(
            model_name='errors',
            index=models.Index(fields=['svc_type'], name='errors_svc_typ_7a98fe_idx'),
        ),
        migrations.AddIndex(
            model_name='errors',
            index=models.Index(fields=['ivoid'], name='errors_ivoid_8468dd_idx'),
        ),
        migrations.AddIndex(
            model_name='errors',
            index=models.Index(fields=['url'], name='errors_url_3cf781_idx'),
        ),
    ]
